name: Build Gold/Silver 97 Reforged German

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Systempakete aktualisieren
        run: |
          sudo apt update
          sudo apt -y install make g++ flex bison git python-is-python3 python3-pip pkg-config libpng-dev
          sudo pip install pypng

      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: RGBDS auschecken
        uses: actions/checkout@v4
        with:
          repository: gbdev/rgbds
          path: rgbds
          ref: 'v0.4.0'

      - name: RGBDS bauen und installieren
        run: |
          cd rgbds
          make Q= LDFLAGS="-Wl,--allow-multiple-definition"
          sudo make install

      - name: Gold ROM bauen
        run: |
          make -j -k all
        working-directory: .

      - name: Freier Speicherplatz prüfen
        run: |
          tools/free_space.awk pokecrystal.map

      - name: Dateien hochladen
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pokemon_g97r
          path: |
            *.gbc
            *.map